# Generated by Django 4.1.2 on 2023-01-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_blog_image_star"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="image",
            new_name="imageBlog",
        ),
        migrations.AlterField(
            model_name="star",
            name="stars",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
