# Generated by Django 4.1.2 on 2023-01-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_rename_image_blog_imageblog_alter_star_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="imageBlog",
            field=models.ImageField(default="/pic.jpg", upload_to=""),
        ),
    ]
