# Generated by Django 4.1.2 on 2023-01-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_alter_blog_imageblog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
