# Generated by Django 4.1.2 on 2023-01-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_alter_blog_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="star",
            name="stars",
        ),
    ]
