# Generated by Django 4.1.2 on 2023-01-16 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500, verbose_name="bio"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, default="/pic.jpg", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
